sudo: false
language: go
services: mongodb
go:
  - 1.x
  - 1.14
  - master
script:
  - go mod download
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin
  - $(go env GOPATH)/bin/golangci-lint run ./...
  - |
      if [ `gofmt -l . | head -1` ]; then
        echo "you must run 'go fmt ./...' to fix formatting"
        exit 1
      fi
  - go test -p 1 -v ./...
notifications:
  email:
    on_success: never
    on_failure: always
